# Generated by Django 3.0.6 on 2020-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.SlugField()),
                ('description', models.SlugField(max_length=200)),
                ('amount', models.SlugField(max_length=20)),
            ],
        ),
    ]
