# Generated by Django 3.0.6 on 2020-05-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
