# Generated by Django 3.0.6 on 2020-06-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_auto_20200611_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
