# Generated by Django 3.0.6 on 2020-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_table_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='loan',
            field=models.CharField(max_length=50),
        ),
    ]
