# Generated by Django 3.0.6 on 2020-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_note_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
