# Generated by Django 3.0.6 on 2020-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_auto_20200615_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
